theme_version: 1.0.5

# Site settings
title:              AlexDesign
logo:               # Logo image URL
description:        Thoughts, Stories and Ideas
baseurl:            '' # The subpath of your site, e.g. /blog
# url:                'https://nubia-jekyll.netlify.com/' # The base hostname & protocol for your site
# twitter:            https://twitter.com/aspirethemes
# facebook:           https://www.facebook.com/aspirethemes
# instagram:          https://www.instagram.com/aspirethemes

markdown:  kramdown
permalink: pretty
paginate:  12
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  Alex:
    name:     Alex Hu
    bio:      Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar: '/images/profile.png'
    # email:    info@aspirethemes.com
    # website:  http://aspirethemes.com
    # github:   https://github.com/aspirethemes
    # twitter:  https://twitter.com/aspirethemes
